name: ci_cd

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.100-preview.2.25164.34'

    - name: restore dependencies
      run: dotnet restore ./App/DiamondApp/DiamondApp.csproj

    - name: build
      run: dotnet build ./App/DiamondApp/DiamondApp.csproj -c Release --no-restore

    - name: test
      run: dotnet test --configuration Release --no-build --no-restore

    - name: publish
      run: dotnet publish ./App/DiamondApp/DiamondApp.csproj -c Release -o ./ --no-build

    - name: copy index.html to 404.html
      run: cp wwwroot/index.html wwwroot/404.html

    - name: add .nojekyll file
      run: touch wwwroot/.nojekyll

    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: wwwroot

